### ISSUE TITLE
Write up guidelines around software license compliance

### ISSUE THREAD

**Issue by DavidEBest** [18F/before-you-ship#157]
Libraries.io has the ability to tell you what license a project is using.

It would be good to have explicit documentation around appropriate licenses for use in our projects.
- What licenses can/can't be used
- Scanning tools

**Comment by its-a-lisa** [comment]
This appears to have been overcome by events because the following statement is in the [intro to github](https://handbook.18f.gov/intro-to-github/) page on the handbook:
The license on every repo must be Creative Commons 0, or CC0. That’s shorthand for Public Domain. TTS is not only committed to working in the public domain by our own policies, but is also committed by law. (Though we are allowed to by law, we don’t trademark our logo.) There are a few exceptions to that rule, so check with #admins-github and #wg-opensource before putting any license other than CC0 on your project. For more details about licensing, see our open source policy, our blog posts about open source, and the Open Source Style guide.

**Comment by afeld** [comment]
This issue was more about the licenses of dependencies, but agreed it hasn't come up and therefore shouldn't be a priority.
