### ISSUE TITLE
Writing Lab Link Broken

### ISSUE THREAD

**Issue by chrispickard** [18F/before-you-ship#200]
On the [before you ship](https://pages.18f.gov/before-you-ship/) page the link for Writing Lab is broken, it leads to https://github.com/18F/writing-lab and looks like it should be https://github.com/18F/writing-lab-guide

**Comment by afeld** [comment]
Hello! The Writing Lab link is actually a private repository (because it's often for working through delicate wording), hence us putting the little 🔒 icon on it (using [Private Eye](https://github.com/18F/private-eye)):

![lock icon](https://cloud.githubusercontent.com/assets/86842/17197571/c9e92168-543b-11e6-97c9-e828d4b78c04.png)

Good feedback that that wasn't obvious though! Have a good one, and keep the bug reports / feedback coming 😃
