### ISSUE TITLE
add access prerequisites for ATO sprint

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#285]
Pulled from the [DRAFT LATO Assessment Cases for Low applications on cloud.gov - version 1.0](https://docs.google.com/spreadsheets/d/18aZNXBaQrq2gIas3-1oLSlokefB8RibWp8wID70qfic/edit#gid=1541480683).

> - [ ] 100% read rights to everything on cloud.gov layer through dashboard.cloud.gov
> - [ ] 100% read rights to everything on application backend layer (ex: for Django, https://APP-NAME.app.cloud.gov/admin/)
> - [ ] GitHub user read rights if any repos are set to private
> - [ ] 100% read rights to the ticketing system (ex: Google Groups, ZenDesk, GitHub Issues, Salesforce, etc), as applicable

**Comment by NoahKunin** [comment]
Seems related to #287. But since staffing has not been stable at all, seems like premature optimization to add to ByS, since the questions is going to always be "give access to who", which people don't find out until they are actually in the assessment process.

Closing until there's an expectation we could no who to give access to beforehand.

**Comment by afeld** [comment]
Wouldn't it make sense to add it as a task to the [ATO Sprint](https://before-you-ship.18f.gov/ato/checklist/#phase-3-ato-sprint) part of the checklist then?
