### ISSUE TITLE
As a project team, I want to know what kind of ATO to pursue

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#303]
It would be helpful for teams (and the sprinting team) to understand when they should do a:

* 90-day ATO
* One-year LATO
* Three-year LATO
* ATO through the partner agency

We should write up considerations, or make a full-blown decision tree.

**Comment by afeld** [comment]
Found out the considerations from Joe Hoyt [here](https://docs.google.com/document/d/179iHsFScDIltH5R6uFX5jztmmIbIIJvLIQV8sG0wMpw/edit#heading=h.8xanx9dga3lz).

**Comment by afeld** [comment]
* [ ] Run the changes by Kurt

**Comment by NoahKunin** [comment]
@afeld Looked at the notes, but I don't really understand. These aren't decisions, but outcomes. All of these are forced decisions. If you need an ATO quickly and for a limited time due to external pressures, do the 90-day. 

Otherwise, Low impact systems get 3 year LATOs. Moderates gets 1 year LATOs per the guides. 

When the partner agency does the ATO, that's decided (or should be) at the time of IAA. I would start (re)-enforcing that rule and not allowing agencies to reverse course at the last moment and expect a 90 day from us, by at this point that's just IMHO.

I can imagine adding a bit more clarity to the third paragraph here (https://before-you-ship.18f.gov/ato/types/) but that will make the guide less evergreen (as a change in the GSA IT LATO guides will need to be backtracked to alter this information). If we're happy with that, it's an easy change.

Lastly, what are the "changes" that are run by Kurt?

**Comment by afeld** [comment]
> These aren't decisions, but outcomes. All of these are forced decisions.

Not sure I follow...? Maybe easier to talk through it in a call.

> I can imagine adding a bit more clarity to the third paragraph here (https://before-you-ship.18f.gov/ato/types/)

Yep! I think expanding that would be fine.

> that will make the guide less evergreen

Yeeeeah, there's obviously a balance between not repeating the canonical sources (and thus risking getting out-of-date), and providing succinct/clear guidance when we don't feel the canonical resources do. The even bigger win would be working with GSA IT to improve the LATO guide, but that obviously requires more coordination. (Not saying that it's "bad" by any means.)

Very possible the LATO guide already covers this satisfactorily, in which case we can just say "refer to X section of the LATO guide".

> what are the "changes" that are run by Kurt?

<img width="968" alt="screen shot 2017-05-17 at 5 22 35 pm" src="https://cloud.githubusercontent.com/assets/86842/26176958/e5dc6da4-3b25-11e7-93ce-8ec826effad0.png">

It can be as simple as sending him a link to the pull request that addresses this issue.

**Comment by NoahKunin** [comment]
@afeld by "outcomes, not decisions" I mean that everything follows form the impact level. You don't decide what ATO you want. You categorize the system, and then everything goes from there. The decision has already been made, given the inherent needs of the system being designed. 

As to Kurt's response above until actual policy has changed and circulated to InSite, we shouldn't change the guide. When/if 90-days are taken off the table, we'll update. Until then, I'll just make the clarifications as scoped above.
