### ISSUE TITLE
explain when re-authorization needs to be done

### ISSUE THREAD

**Issue by afeld** [18F/before-you-ship#94]
It's not clear to people what changes to a project should constitute a "new" ATO being created, though maybe it's irrelevant once we move to [continuous authorization](https://pages.18f.gov/before-you-ship/ato/types/#continuous-authorization)? I **assume** in that case they have a System Security Plan that stays up-to-date throughout the development cycle, and new action only needs to be taken if they change [level](https://pages.18f.gov/before-you-ship/ato/levels/)? @NoahKunin Does that sound right? Any other guidance here?

Raised because of https://github.com/18F/DevOps/issues/542.

/cc @gboone

**Comment by afeld** [comment]
Ah, I suppose there is some guidance in there already:

https://github.com/18F/before-you-ship/blob/d95cc6b60151c2d3cdca56e4253d5a921d2e348e/_pages/ato.md#the-ato-process

@gboone I leave it up to you about whether that's enough info to close this issue.

**Comment by gboone** [comment]
I think maybe some examples might be useful:

> Encryption methodologies

Does that mean HTTPS implementation changes like adding HTTP/2? Or does that apply to database encryption within the application? Or both? From what I understand from @thecapacity in #95 it sounds like the answer is it only applies to encryption within the application.

> A web framework having new backend administrative frameworks

Does moving the same site from no-Federalist to Federalist count? Or does it have to be something more major like moving from pure static site to a database-driven application (e.g., Rails, Django, or a CMS)? Seems like from #432 the answer is the second.

**Comment by thecapacity** [comment]
I think it might be helpful to break out the "ATO" shortcut - I view an ATO as a combination of "accreditation" (does something do what it says it does) and "authorization" (do we think this is a good idea).

In my experience "accreditation" can be inherited (e.g. FedRAMP, ISO, etc) but "authorization" is still something the agency is responsible for... (e.g. we authorize the use of ServiceX)

So cloud.gov would both accredite and authorize something like the methods used for secure transport - e.g. saying we leverage HTTP/2 and here's how, but an agency that wanted to host anything on cloud.gov would still need to authorize that for their own system - because they have to know/validate that it's appropriate for their intended use.

**Comment by afeld** [comment]
This seems to be very subjective, and I think [the guidance we have](https://pages.18f.gov/before-you-ship/ato/#re-authorization) is pretty good. Closing for now.
